name: Build and deploy backend

on:
    push:
        branches: [main]
    # TODO: this should build-but-not-deploy for pull_request
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        container: ghcr.io/railwayapp/cli:latest
        env:
            SERVICE_ID: 91006518-040f-492e-9678-55b4cc73431f
            RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Deploy to Railway
              run: railway up --service=${{ env.SERVICE_ID }}
